export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAILURE = "FETCH_PRODUCT_FAILURE";
export const INCREMENT_PRODUCT_STOCK = "INCREMENT_PRODUCT_STOCK";
export const DECREMENT_PRODUCT_STOCK = "DECREMENT_PRODUCT_STOCK";
export const NEW_PRODUCT_STOCK = "NEW_PRODUCT_STOCK";
export const SET_SEARCH_ITEMS = "SET_SEARCH_ITEMS";

// sort types
export const SORT_BY_PRODUCT_NAME_ASC = "SORT_BY_PRODUCT_NAME_ASC";
export const SORT_BY_PRODUCT_NAME_DEC = "SORT_BY_PRODUCT_NAME_DEC";
export const SORT_BY_PRODUCT_ID_ASC = "SORT_BY_PRODUCT_ID_ASC";
export const SORT_BY_PRODUCT_ID_DEC = "SORT_BY_PRODUCT_ID_DEC";
export const SORT_BY_PRODUCT_QUANTITY_ASC = "SORT_BY_PRODUCT_QUANTITY_ASC";
export const SORT_BY_PRODUCT_QUANTITY_DEC = "SORT_BY_PRODUCT_QUANTITY_DEC";
